version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432